#!/bin/sh
#

[ -r /etc/lsb-release ] && . /etc/lsb-release

if [ -z "$DISTRIB_DESCRIPTION" ] && [ -x /usr/bin/lsb_release ]; then
	# Fall back to using the very slow lsb_release utility
	DISTRIB_DESCRIPTION=$(lsb_release -s -d)
fi

UPTIME=`uptime | awk '{if ($4 == "day," || $4 == "days,") print $3, $4, $5; else print $3}' | awk -F: '{print $1, "hrs", $2, "mins"}' | sed 's/,//g'`

LOADAVG=`uptime | awk '{if ($4 == "day," || $4 == "days,") print $10, $11, $12; else print $8, $9, $10}'`

PROCCOUNT=`ps -l | wc -l`
PROCCOUNT=`expr $PROCCOUNT - 4`
IP=$(/sbin/ifconfig eth0 | grep "inet addr" | awk -F: '{print $2}' | awk '{print $1}')

echo -e "
\033[0;35m-----------------: \033[0;37mSystem Info\033[0;35m :-------------------\033[0;37m
 Hostname: `hostname`
 Address: \033[0;32m$IP\033[0;37m
 Distro: $DISTRIB_DESCRIPTION
 Kernel: `uname -r`
 Uptime: $UPTIME
 Load Avgs: $LOADAVG
 Processes: $PROCCOUNT
\033[0;35m-----------------: \033[0;37mMemory Info\033[0;35m :-------------------\033[0;37m
 Total: `cat /proc/meminfo | grep MemTotal | awk {'print $2'}` kB
 Free: `cat /proc/meminfo | grep MemFree | awk {'print $2'}` kB
 Lowest: `cat /proc/meminfo | grep LowFree | awk {'print $2'}` kB
\033[0;35m-----------------: \033[0;37m Disk Info\033[0;35m :--------------------\033[0;37m"
df -h
